name: Spellcheck (Fast Feedback)

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    name: VerificaÃ§Ã£o OrtogrÃ¡fica
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ” Rodar Linter de Ortografia
        uses: crate-ci/typos@master
        with:
          ignore_hidden: false
